### ISSUE TITLE
Error while build with OpenCV 3.1

### ISSUE THREAD

**Issue by Diadlo** [TokTok/toxcore#158]
Can build toxcore with tests. Have an error:
```
CMakeFiles/av_test.dir/testing/av_test.c.o: In function `cvPointFrom32f':
av_test.c:(.text+0x549): undefined reference to `cvRound'
av_test.c:(.text+0x55f): undefined reference to `cvRound'
CMakeFiles/av_test.dir/testing/av_test.c.o: In function `cvReadInt':
av_test.c:(.text+0xda5): undefined reference to `cvRound'
CMakeFiles/av_test.dir/testing/av_test.c.o: In function `cvEllipseBox':
av_test.c:(.text+0x1011): undefined reference to `cvRound'
av_test.c:(.text+0x1033): undefined reference to `cvRound'
```

Seems, OpenCV 3.1 hasn't cvRound function

**Comment by iphydf** [comment]
It does, but only in C++, but it still defines some inline C functions that use cvRound. Try the [iphydf/opencv3](https://github.com/iphydf/toxcore/tree/opencv3) branch.

**Comment by Diadlo** [comment]
@iphydf Yes, it fixed. Thanks

**Comment by iphydf** [comment]
https://github.com/opencv/opencv/issues/6585 - either we use C++ (#160 does this) or require `opencv<3`.

**Comment by iphydf** [comment]
Fixed in #160.
